### ISSUE TITLE
Change flashloan provider

### ISSUE THREAD

**Issue by playfaculty** [xrchz/rocketarb#14]
Euler was hacked and completely drained so their flashloan provider is pretty useless now;

https://nitter.fly.dev/peckshield/status/1635229594596036608#m

https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2?a=0x27182842e098f60e3d576794a5bffb0777e025d3

**Comment by xrchz** [comment]
This one works for now: https://etherscan.io/address/0xE46BFe6F559041cc1323dB3503a09c49fb5d8828
I'm happy to take a PR to change the default if someone wants to write that.

**Comment by 3cl1ps** [comment]
is it just an copy/paste somewhere with the new flashloan provider or rocketarb is not useable right now ?

**Comment by ejmahler** [comment]
#15 adds a new flash loan provider - so now we have two available, 0x346b and the new RocketUniArb

**Comment by xrchz** [comment]
It is usable, you can use one of the other providers with the `--arb-contract` or `-b` flag.

**Comment by 3cl1ps** [comment]
i still got a BlockPassedWithoutInclusion when i'm using the default (no args).
i tried several times, should i increase the fee or priority fee ?

**Comment by xrchz** [comment]
The default (no args) is not going to work as long as Euler is down. You can see why it fails if you use the `--dry-run` argument and look for the revert message.
