### ISSUE TITLE
Does rocketarb work on testnet?

### ISSUE THREAD

**Issue by monkey-jsun** [xrchz/rocketarb#6]
Just want to try it out first if possible.  Thanks!

**Comment by xrchz** [comment]
No it does not. It can't easily be made to work on testnet unless there's a testnet version of the 1inch API (I don't know about this existing).

**Comment by monkey-jsun** [comment]
Makes sense.  

README says "Stop before the final ARE YOU SURE... prompt and cancel it.".  There are so many steps.  Is it referring to the "rocketpool node deposit" step? 

Also, suppose I cancel the last prompt but then I don't want to do arb anymore.  Can I re-run the same command again?

**Comment by xrchz** [comment]
You might get better help in the Rocketpool Discord server.
Yes it's referring to `rocketpool node deposit` step when saying to cancel it. If you cancel it you can re-run it.
