### ISSUE TITLE
Better error handling for 1inch

### ISSUE THREAD

**Issue by yorickdowne** [xrchz/rocketarb#8]
Or even better, figuring out why it happens and changing that so it doesn't :)

```
Got 500 from 1inch
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.3.0
```

Suggest having an error handler here that prints out the code and also the message - 1inch usually delivers a reason it returned a 500.

**Comment by yorickdowne** [comment]
Maybe as simple as `Got ${res.statusCode} from 1inch with message ${res.statusMessage}`

Alas 1inch has been giving me an `Internal Server Error` most of the time.

**Comment by xrchz** [comment]
Uncaught errors are par for the course in this script - but including the status message seems good - I've done that.
